### ISSUE TITLE
ERROR ORA-65015: missing or invalid container name.

### ISSUE THREAD

**Issue by sonnguyen-dba** [averemee-si/oracdc#10]
Hi Aleksej,

Could you please helping with issue initload tables from schema in pdb?

[2020-11-15 15:45:08,338] INFO Rewinding LogMiner ResultSet to first position after SCN = 0, RS_ID = 'null', SSN = 0. (eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread:186)
[2020-11-15 15:45:08,786] INFO Total records scipped while rewinding: 0, elapsed time ms: 213 (eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread:220)
[2020-11-15 15:45:08,786] INFO BEGIN: OraCdcInitialLoadThread.run() (eu.solutions.a2.cdc.oracle.OraCdcInitialLoadThread:81)
[2020-11-15 15:45:08,787] INFO WorkerSourceTask{id=oracdc-beta-data-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:200)
[2020-11-15 15:45:08,931] ERROR ORA-65015: missing or invalid container name

java.sql.SQLException: ORA-65015: missing or invalid container name

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
        at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265)
        at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86)
        at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
        at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358)
        at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
        at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
        at oracle.ucp.jdbc.proxy.oracle$1ucp$1jdbc$1proxy$1oracle$1StatementProxy$2oracle$1jdbc$1internal$1OracleCallableStatement$$$Proxy.execute(Unknown Source)
        at eu.solutions.a2.cdc.oracle.OraTable4InitialLoad.readTableData(OraTable4InitialLoad.java:549)
        at eu.solutions.a2.cdc.oracle.OraCdcInitialLoadThread.lambda$run$0(OraCdcInitialLoadThread.java:93)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: Error : 65015, Position : 28, Sql = alter session set container=:1 , OriginalSql = alter session set container=?, Error Msg = ORA-65015: missing or invalid container name

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
        ... 22 more
 (eu.solutions.a2.cdc.oracle.OraTable4InitialLoad:579)

[2020-11-15 15:45:15,604] INFO WorkerSourceTask{id=oracdc-beta-data-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:398)

Regards,
Son

**Comment by averemee-si** [comment]
Hi Son,

Could you please:
1) Review latest **oracdc**'s README and [Quickstart Guide](https://github.com/averemee-si/oracdc/wiki/Quick-start-guide-for-any-distribution-of-Apache-Kafka) for changes in account setup for CDB. Most important change is addition of **SET CONTAINER** privilege. Do not forget to grant it! For example:
```
grant SET CONTAINER to C##ORACDC;
```
2) Clone latest **oracdc** code which contains [fix alter session set CONTAINER=](https://github.com/averemee-si/oracdc/commit/9fb6bd36b81723d07f8dfb15eccfddceefd0c7a5) and retest issue

Regards,
Aleksei

**Comment by sonnguyen-dba** [comment]
Hi Aleksej,
I was retested with latest oracdc but now have issue.

2020-11-16 20:05:22,458] INFO Adding archived log /fast_recovery_area/oraetown/archivelog/2020_11_16/o1_mf_1_2488_hv4gfw6b_.arc thread# 1 sequence# 2488 first change number 585748742406 next log first change 585750308759 (eu.solutions.a2.cdc.oracle.OraLogMiner:167)
[2020-11-16 20:05:22,478] INFO Rewinding LogMiner ResultSet to first position after SCN = 585750249318, RS_ID = ' 0x0009b8.000da38a.02a8 ', SSN = 0. (eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread:186)
[2020-11-16 20:05:29,950] INFO WorkerSourceTask{id=oracdc-beta-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:398)
[2020-11-16 20:05:29,951] INFO WorkerSourceTask{id=oracdc-beta-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:415)
[2020-11-16 20:05:34,684] ERROR Incorrect rewind to SCN = 585750249318, RS_ID = ' 0x0009b8.000da38a.02a8 ', SSN = 0 (eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread:214)
[2020-11-16 20:05:34,684] ERROR Unable to start oracdc logminer task! (eu.solutions.a2.cdc.oracle.OraCdcLogMinerTask:482)
[2020-11-16 20:05:34,686] ERROR Incorrect rewind operation!!!
java.sql.SQLException: Incorrect rewind operation!!!
        at eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread.rewind(OraCdcLogMinerWorkerThread.java:216)
        at eu.solutions.a2.cdc.oracle.OraCdcLogMinerTask.start(OraCdcLogMinerTask.java:478)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:199)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
 (eu.solutions.a2.cdc.oracle.OraCdcLogMinerTask:483)
[2020-11-16 20:05:34,686] INFO WorkerSourceTask{id=oracdc-beta-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:398)
[2020-11-16 20:05:34,687] INFO WorkerSourceTask{id=oracdc-beta-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:415)
[2020-11-16 20:05:34,687] ERROR WorkerSourceTask{id=oracdc-beta-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: Incorrect rewind operation!!!
        at eu.solutions.a2.cdc.oracle.OraCdcLogMinerTask.start(OraCdcLogMinerTask.java:484)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:199)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLException: Incorrect rewind operation!!!
        at eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread.rewind(OraCdcLogMinerWorkerThread.java:216)
        at eu.solutions.a2.cdc.oracle.OraCdcLogMinerTask.start(OraCdcLogMinerTask.java:478)
        ... 8 more
[2020-11-16 20:05:34,690] ERROR WorkerSourceTask{id=oracdc-beta-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)

**Comment by averemee-si** [comment]
Hi Son,

Did you delete oracdc.state file and Kafka offset file (specified by offset.storage.file.filename parameter)?

**Comment by sonnguyen-dba** [comment]
Thank Aleksej, I was deleted Kafka offset file -> ok, but  have new issue

[2020-11-16 20:43:03,414] INFO Adding archived log /fast_recovery_area/oraetown/archivelog/2020_11_15/o1_mf_1_2482_hv0pwjsc_.arc thread# 1 sequence# 2482 first change number 585740691238 next log first change 585742418555 (eu.solutions.a2.cdc.oracle.OraLogMiner:167)
[2020-11-16 20:43:03,431] INFO BEGIN: OraCdcInitialLoadThread.run() (eu.solutions.a2.cdc.oracle.OraCdcInitialLoadThread:81)
[2020-11-16 20:43:03,432] INFO BEGIN: OraCdcLogMinerWorkerThread.run() (eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread:229)
[2020-11-16 20:43:03,432] INFO WorkerSourceTask{id=oracdc-beta-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:200)
[2020-11-16 20:43:03,579] INFO Table BETAPDB:ERP.ACCOUNTTEST (DEPENDENCY='DISABLED') initial load (read phase) started. (eu.solutions.a2.cdc.oracle.OraTable4InitialLoad:558)
[2020-11-16 20:43:03,581] ERROR Table BETAPDB:ERP.ACCOUNTTEST not found while performing initial load! (eu.solutions.a2.cdc.oracle.OraTable4InitialLoad:576)
[2020-11-16 20:43:03,581] INFO END: OraCdcInitialLoadThread.run(), elapsed time 149 ms (eu.solutions.a2.cdc.oracle.OraCdcInitialLoadThread:112)
[2020-11-16 20:43:04,483] INFO Initial load completed (eu.solutions.a2.cdc.oracle.OraCdcLogMinerTask:511)
[2020-11-16 20:43:10,586] INFO WorkerSourceTask{id=oracdc-beta-erp-tgddnews-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:398)
[2020-11-16 20:43:10,587] INFO WorkerSourceTask{id=oracdc-beta-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:415)

Regards,
Son

**Comment by averemee-si** [comment]
Hi Son,

Message "Table BETAPDB:ERP.ACCOUNTTEST not found while performing initial load!" means that user running connector don't have permissions for select from this table. You need to grant select permission for selecting from BETAPDB to common user running connector.

Regards,
Aleksei

**Comment by sonnguyen-dba** [comment]
Thanks Aleksej, Now oracdc working good!
Regards,
Son
