### ISSUE TITLE
UniversalPoolconnectionException

### ISSUE THREAD

**Issue by shrikant28** [averemee-si/oracdc#14]
Hi Team,
With using this example property reference, i have tried to connect to oracle 12c.
But it is continuously giving below error.

Caused by: oracle.ucp.UniversalConnectionPoolException: Error during pool creation in Universal Connection Pool Manager MBean: oracle.ucp.UniversalConnectionPoolException: Error during pool
 creation in Universal Connection Pool Manager: java.sql.SQLException: Invalid Universal Connection Pool configuration: oracle.ucp.UniversalConnectionPoolException: Universal Connection Poo
l already exists in the Universal Connection Pool Manager. Universal Connection Pool cannot be added to the Universal Connection Pool Manager
        at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:336)
        at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:59)
        at oracle.ucp.admin.UniversalConnectionPoolManagerMBeanImpl.createConnectionPool(UniversalConnectionPoolManagerMBeanImpl.java:304)
        at oracle.ucp.jdbc.PoolDataSourceImpl.createPool(PoolDataSourceImpl.java:1263)
        at oracle.ucp.jdbc.PoolDataSourceImpl.startPool(PoolDataSourceImpl.java:916)
        ... 21 more
Caused by: oracle.ucp.UniversalConnectionPoolException: Error during pool creation in Universal Connection Pool Manager: java.sql.SQLException: Invalid Universal Connection Pool configurati
on: oracle.ucp.UniversalConnectionPoolException: Universal Connection Pool already exists in the Universal Connection Pool Manager. Universal Connection Pool cannot be added to the Universa
l Connection Pool Manager
        at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:336)
        at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:59)
        at oracle.ucp.admin.UniversalConnectionPoolManagerBase.createConnectionPool(UniversalConnectionPoolManagerBase.java:819)
        at oracle.ucp.admin.UniversalConnectionPoolManagerMBeanImpl.createConnectionPool(UniversalConnectionPoolManagerMBeanImpl.java:291)
        ... 23 more

**Comment by averemee-si** [comment]
Hello,

Could you please:
1) Provide connector configuration file;
2) Full error stack
3) What distribution of Apache Kafka are you working with: Confluent, OpenSource, other?

Thanks,
Aleksei

**Comment by shrikant28** [comment]
Hi ,
I am using confluent kafka.
below is connection json.

please help me here.
{
  "schema.registry.url": "http://zapalnrapp1079.corp.dsarena.com:8081",
  "name": "test-cdc-connector",
  "connector.class": "eu.solutions.a2.cdc.oracle.OraCdcLogMinerConnector",
  "tasks.max": "1",
  "key.converter": "org.apache.kafka.connect.storage.StringConverter",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "transforms": "",
  "config.action.reload": "none",
  "errors.log.enable": "true",
  "errors.log.include.messages": "true",
  "a2.jdbc.url": "",
  "a2.jdbc.username": "",
  "a2.jdbc.password": "",
  "a2.kafka.topic": "test-topic",
  "a2.poll.interval": "1000",
  "a2.batch.size": "1000",
  "a2.schema.type": "debezium",
  "a2.topic.prefix": "",
  "a2.include": "SSAMCERADM.PERSONS",
  "a2.redo.count": "1",
  "a2.redo.size": "1",
  "a2.first.change": "1",
  "a2.tmpdir": "",
  "a2.standby.activate": "false",
  "a2.standby.wallet.location": "V$DATABASE.OPEN_MODE = MOUNTED",
  "a2.standby.tns.admin": "V$DATABASE.OPEN_MODE = MOUNTED",
  "a2.standby.tns.alias": "V$DATABASE.OPEN_MODE = MOUNTED",
  "a2.persistent.state.file": "$TMPDIR/oracdc.state",
  "a2.oracdc.schemas": "true",
  "a2.initial.load": "IGNORE",
  "a2.topic.name.style": "TABLE ",
  "a2.topic.name.delimiter": "_",
  "a2.table.list.style": "static",
  "a2.process.lobs": "false",
  "a2.connection.backoff": "30000"
}

**Comment by averemee-si** [comment]
Hello,

Could you please review [Quick start guide for any distribution of Apache Kafka](https://github.com/averemee-si/oracdc/wiki/Quick-start-guide-for-any-distribution-of-Apache-Kafka) and follow instructions from this document.
For initial configuration please set only following parameters:
a2.jdbc.url=**jdbc:oracle:thin:@//<ORACLE_HOST>:<ORACLE_PORT>/<ORACLE_SID>**
a2.jdbc.username=**<ORACLE-USER>**
a2.jdbc.password=**<PASSWORD-OF-ORACLE-USER>**
a2.include=**SSAMCERADM.PERSONS**

**oracdc** will set other parameters to default values.

Hope this helps!

Regards,
Aleksei

**Comment by shrikant28** [comment]
Still i am getting same log as above.

**Comment by averemee-si** [comment]
Hello,

Could you please provide updated connector's config

Thanks!

Regards,
Aleksei

**Comment by shrikant28** [comment]
{
"schema.registry.url": "http://xyz.abc.com:8081",
"name": "test-cdc-connector",
"connector.class": "eu.solutions.a2.cdc.oracle.OraCdcLogMinerConnector",
"tasks.max": "1",
"key.converter": "org.apache.kafka.connect.storage.StringConverter",
"value.converter": "io.confluent.connect.avro.AvroConverter",
"a2.jdbc.url": "",
"a2.jdbc.username": "",
"a2.jdbc.password": "",
"a2.kafka.topic": "test-topic",
"a2.poll.interval": "1000",
"a2.batch.size": "1000",
"a2.schema.type": "kafka",
"a2.topic.prefix": "",
"a2.include": "SSAMCERADM.PERSONS",
"a2.oracdc.schemas": "false"
}

**Comment by averemee-si** [comment]
Hello,

You must specify non-empty valid values for **a2.jdbc.url**,  **a2.jdbc.username**, and **a2.jdbc.password** or parameters for Oracle Wallet.
Without valid values for these parameters connector is unable to connect to Oracle RDBMS.

P.S. I'm located in CET TZ and we can schedule short online meeting for checking your environment.

Regards,
Aleksei

**Comment by shrikant28** [comment]
Hi Aleksei,
Thanks for response, Actually i am passing it in my env, but i have scrapped that here due to some policies.

Thanks

**Comment by averemee-si** [comment]
Hello,

OK, thanks.
Could you please upload **full** (not part of it!) connector log

Regards,
Aleksei

**Comment by shrikant28** [comment]
Hi,

Same log as above.
Caused by: oracle.ucp.UniversalConnectionPoolException: Error during pool creation in Universal Connection Pool Manager MBean: oracle.ucp.UniversalConnectionPoolException: Error during pool
creation in Universal Connection Pool Manager: java.sql.SQLException: Invalid Universal Connection Pool configuration: oracle.ucp.UniversalConnectionPoolException: Universal Connection Poo
l already exists in the Universal Connection Pool Manager. Universal Connection Pool cannot be added to the Universal Connection Pool Manager
at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:336)
at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:59)
at oracle.ucp.admin.UniversalConnectionPoolManagerMBeanImpl.createConnectionPool(UniversalConnectionPoolManagerMBeanImpl.java:304)
at oracle.ucp.jdbc.PoolDataSourceImpl.createPool(PoolDataSourceImpl.java:1263)
at oracle.ucp.jdbc.PoolDataSourceImpl.startPool(PoolDataSourceImpl.java:916)
... 21 more
Caused by: oracle.ucp.UniversalConnectionPoolException: Error during pool creation in Universal Connection Pool Manager: java.sql.SQLException: Invalid Universal Connection Pool configurati
on: oracle.ucp.UniversalConnectionPoolException: Universal Connection Pool already exists in the Universal Connection Pool Manager. Universal Connection Pool cannot be added to the Universa
l Connection Pool Manager
at oracle.ucp.util.UCPErrorHandler.newUniversalConnectionPoolException(UCPErrorHandler.java:336)
at oracle.ucp.util.UCPErrorHandler.throwUniversalConnectionPoolException(UCPErrorHandler.java:59)
at oracle.ucp.admin.UniversalConnectionPoolManagerBase.createConnectionPool(UniversalConnectionPoolManagerBase.java:819)
at oracle.ucp.admin.UniversalConnectionPoolManagerMBeanImpl.createConnectionPool(UniversalConnectionPoolManagerMBeanImpl.java:291)
... 23 more

**Comment by averemee-si** [comment]
Hello

This is not full log, full log is required.
This fragment contains:
 **java.sql.SQLException: Invalid Universal Connection Pool configuration**
but I didn't see details about  **java.sql.SQLException** or configuration settings - they are in **FULL** log, but I see only some lines.
To continue - please upload or send me **FULL** log.

Regards,
Aleksei

**Comment by averemee-si** [comment]
I am closing this issue due to no response from @shrikant28 within two weeks
