### ISSUE TITLE
ORA-02396: exceeded maximum idle time, please connect again

### ISSUE THREAD

**Issue by sonnguyen-dba** [averemee-si/oracdc#17]
Hi Aleksej,
I have facing issue exceeded maximum idle time.
User I was set idle_time to unlimited.

```sql
SQL> SELECT * FROM DBA_PROFILES where profile = 'MONITORING_PROFILE' and
RESOURCE_NAME='IDLE_TIME';

PROFILE                                     RESOURCE_NAME    RESOURCE    LIMIT
---------------------------   ---------------------- ------------  ------------------------------------
MONITORING_PROFILE             IDLE_TIME                  KERNEL       UNLIMITED


USERNAME                       PROFILE                            RESOURCE_NAME                   LIMIT
---------------- -----------------------------  ----------------------------  ----------------------------------------
CDC                            MONITORING_PROFILE           IDLE_TIME                        UNLIMITED
```
- trace

[2021-04-29 07:25:21,157] INFO WorkerSourceTask{id=oracdc-oracle-ov-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:426)
[2021-04-29 07:25:21,157] INFO WorkerSourceTask{id=oracdc-oracle-ov-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:443)
[2021-04-29 07:25:21,157] INFO WorkerSourceTask{id=oracdc-oracle-ov-0} Finished commitOffsets successfully in 0 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:525)
[2021-04-29 07:25:23,518] ERROR ORA-02396: exceeded maximum idle time, please connect again
 (eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread:631)
[2021-04-29 07:25:23,519] ERROR SQL errorCode = 2396, SQL state = '61000' (eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread:634)
[2021-04-29 07:25:23,521] ERROR ORA-02396: exceeded maximum idle time, please connect again

java.sql.SQLException: ORA-02396: exceeded maximum idle time, please connect again

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:91)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1012)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
        at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1426)
        at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3713)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1167)
        at oracle.ucp.jdbc.proxy.oracle$1ucp$1jdbc$1proxy$1oracle$1StatementProxy$2oracle$1jdbc$1internal$1OraclePreparedStatement$$$Proxy.executeQuery(Unknown Source)
at eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread.run(OraCdcLogMinerWorkerThread.java:357)
Caused by: Error : 2396, Position : 0, Sql = select O.OBJECT_ID, T.OWNER, T.TABLE_NAME, T.DEPENDENCIES,
       decode(O.OBJECT_TYPE, 'TABLE', 'Y', 'N') IS_TABLE,
       decode(O.OBJECT_TYPE, 'TABLE', O.OBJECT_ID,
         (select PT.OBJECT_ID
          from   DBA_OBJECTS PT
          where  PT.OWNER=O.OWNER
            and  PT.OBJECT_NAME=O.OBJECT_NAME
            and  PT.OBJECT_TYPE='TABLE')) PARENT_OBJECT_ID
from   DBA_OBJECTS O, DBA_TABLES T
where  O.OBJECT_TYPE in ('TABLE', 'TABLE PARTITION', 'TABLE SUBPARTITION')
  and  O.TEMPORARY='N'
  and  O.OWNER not in ('SYS','SYSTEM','MGDSYS','OJVMSYS','AUDSYS','OUTLN','APPQOSSYS','DBSNMP','CTXSYS','ORDSYS','ORDPLUGINS','ORDDATA','MDSYS','OLAPSYS','GGSYS','XDB','GSMADMIN_INTERNAL','DBSFWUSER','LBACSYS','DVSYS','WMSYS')
  and  O.OWNER=T.OWNER
  and  O.OBJECT_NAME=T.TABLE_NAME
  and  O.OBJECT_ID=:1
 and ((O.OWNER='USER' and O.OBJECT_NAME='PM_OV')), OriginalSql = select O.OBJECT_ID, T.OWNER, T.TABLE_NAME, T.DEPENDENCIES,
       decode(O.OBJECT_TYPE, 'TABLE', 'Y', 'N') IS_TABLE,
       decode(O.OBJECT_TYPE, 'TABLE', O.OBJECT_ID,
         (select PT.OBJECT_ID
          from   DBA_OBJECTS PT
          where  PT.OWNER=O.OWNER
            and  PT.OBJECT_NAME=O.OBJECT_NAME
            and  PT.OBJECT_TYPE='TABLE')) PARENT_OBJECT_ID
from   DBA_OBJECTS O, DBA_TABLES T
where  O.OBJECT_TYPE in ('TABLE', 'TABLE PARTITION', 'TABLE SUBPARTITION')
  and  O.TEMPORARY='N'
  and  O.OWNER not in ('SYS','SYSTEM','MGDSYS','OJVMSYS','AUDSYS','OUTLN','APPQOSSYS','DBSNMP','CTXSYS','ORDSYS','ORDPLUGINS','ORDDATA','MDSYS','OLAPSYS','GGSYS','XDB','GSMADMIN_INTERNAL','DBSFWUSER','LBACSYS','DVSYS','WMSYS')
  and  O.OWNER=T.OWNER
  and  O.OBJECT_NAME=T.TABLE_NAME
  and  O.OBJECT_ID=?
 and ((O.OWNER='USER' and O.OBJECT_NAME='PM_OV')), Error Msg = ORA-02396: exceeded maximum idle time, please connect again
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
        ... 16 more
 (eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread:637)
[2021-04-29 07:25:23,521] INFO Stopping oracdc logminer source task. (eu.solutions.a2.cdc.oracle.OraCdcLogMinerTask:634)
[2021-04-29 07:25:23,722] INFO Saving oracdc state to /data/oracdc/state/oracdc_ov.state file... (eu.solutions.a2.cdc.oracle.OraCdcLogMinerTask:684)
[2021-04-29 07:25:23,730] INFO oracdc state saved to /data/oracdc/state/oracdc_ov.state file, elapsed 8 ms (eu.solutions.a2.cdc.oracle.OraCdcLogMinerTask:747)
[2021-04-29 07:25:31,158] INFO WorkerSourceTask{id=oracdc-oracle-ov-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:426)
[2021-04-29 07:25:31,158] INFO WorkerSourceTask{id=oracdc-oracle-ov-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:443)
[2021-04-29 07:25:31,159] INFO WorkerSourceTask{id=oracdc-oracle-ov-0} Finished commitOffsets successfully in 1 ms (org.apache.kafka.connect.runtime.WorkerSourceTask:525)

Regards,
Son

**Comment by averemee-si** [comment]
Hi Son,

Working on it

Regards,
Aleksei

**Comment by averemee-si** [comment]
Hi Son,

Unfortunately I was unable to reproduce ORA-2396 in-house. I've made fix based only on stacktrace. Could you please try code which includes commit "[ORA-2396 fix](https://github.com/averemee-si/oracdc/commit/aa40ab68d77155697c63c831adafbf8456bd86a2)" - hope this helps...

Regards,
Aleksei

**Comment by sonnguyen-dba** [comment]
Hi Aleksei,
Thank you very much.
Regards,
Son
