### ISSUE TITLE
integration with azure event hub 

### ISSUE THREAD

**Issue by claudio-navarro-martinez** [averemee-si/oracdc#24]
Hi, I am trying to install your oracle cdc connector but I am having issues.
My setup is an Azure Event Hub, a local db in my laptop and Kafka Connector configured in my laptop. I am able to start Kafka Connector to talk to AZ EH , but at the time of starting the worker for oracle cdc it hangs:

Waiting {} ms for UCP initialization...  

I tried with Debezium unsuccesfully as well, so not sure where is the issue.

# file connector.properties
{
    "name": "oracdc-testa2",
    "config": {
        "connector.class" : "eu.solutions.a2.cdc.oracle.OraCdcLogMinerConnector",
        "tasks.max" : "1",
        "a2.include" : "OT.%",
        "a2.jdbc.url" : "jdbc:oracle:thin:@//81.20.20.16:49154/ORACLECDB.localdomain",
        "a2.jdbc.username" : "C##DBZUSER",
        "a2.jdbc.password" : "xxxxx",
        "a2.kafka.topic" : "oracle-cdc-claudio",
        "a2.schema.type" : "debezium",
        "a2.tempdir" : "/tmp"
    }
}
 

 ################ file connect-distributed.properties

bootstrap.servers=aehw.servicebus.windows.net:9093 
group.id=connect-cluster-group

# connect internal topic names, auto-created if not exists
config.storage.topic=connect-cluster-configs
offset.storage.topic=connect-cluster-offsets
status.storage.topic=connect-cluster-status

# internal topic replication factors - auto 3x replication in Azure Storage
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

rest.advertised.host.name=connect
offset.flush.interval.ms=10000

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter

# required EH Kafka security settings
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://cnm1aehw.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxxxxxxxxxxxxxxxxxxxxx";

producer.security.protocol=SASL_SSL
producer.sasl.mechanism=PLAIN
producer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://cnm1aehw.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

plugin.path=/home/claudio/kafka.azure/kafka_2.12-3.0.0/libs # path to the libs directory within the Kafka release

**Comment by averemee-si** [comment]
Hi Claudio,

Did you check connectivity to `jdbc:oracle:thin:@//81.20.20.16:49154/ORACLECDB.localdomain` using 
`nc -v 81.20.20.16 49154`
and `tnsping` command?

Could you please also upload last lines of connector log.

Regards,
Aleksei

**Comment by claudio-navarro-martinez** [comment]
Hi Aleksei

my setup is :
laptop 192.168.0.163 (internal home IP), NAT-ed to 81.20.20.16. Also my
Oracle database is running in a Docker container in this laptop. Port
exposed 49154:1521
            from this laptop I run ./bin/connect-distributed.sh
./config/connect-distributed.properties and it works fine, gets the EH in
Azure and creates 3 topics
             then I run curl -X POST -H "Content-Type: application/json"
--data @a2.oracle.cdc.properties http://localhost:8083/connectors
{
    "name": "oracdc-testa2",
    "config": {
"connector.class" : "eu.solutions.a2.cdc.oracle.OraCdcLogMinerConnector",
"tasks.max" : "1",
"a2.include" : "OT.%",
"a2.jdbc.url" : "jdbc:oracle:thin:@//81.20.20.16:49154/ORCLCDB.localdomain",
"a2.jdbc.username" : "C##DBZUSER",
"a2.jdbc.password" : "dbz",
"a2.kafka.topic" : "oracle-cdc-claudio",
"a2.schema.type" : "debezium",
"a2.tempdir" : "/tmp"
    }
}

nc works fine from my laptop, also I wrote a small java program using the
jdbc url and connects fine to the db. That program connects fine to the db
from an Azure VM. Also nc connects fine as well.
nc -v 81.20.20.16 49154

Doing nc -v 192.168.0.163 49154 works fine as well from my laptop or any
other box sitting in my home network.

So not sure what is wrong? maybe the fact that I am running it from home
NAT-ing the IPs? maybe Kafka Connect can't manage 2 different space
addresses at the same time?

I tried with the CDC Debezium connector unsuccessfully as well.

Thanks a lot for answering my email as I am a bit desperate and I can't
find much info for it on the internet.

[2021-11-10 09:37:15,860] INFO [oracdc-testa2|worker] Instantiated
connector oracdc-testa2 with version 0.9.8.3 of type class
eu.solutions.a2.cdc.oracle.OraCdcLogMinerConnector
(org.apache.kafka.connect.runtime.Worker:278)
[2021-11-10 09:37:15,861] INFO [oracdc-testa2|worker] Finished creating
connector oracdc-testa2 (org.apache.kafka.connect.runtime.Worker:304)
[2021-11-10 09:37:15,863] INFO [Worker clientId=connect-1,
groupId=connect-cluster-group] Finished starting connectors and tasks
(org.apache.kafka.connect.runtime.distributed.DistributedHerder:1406)
[2021-11-10 09:37:15,864] INFO [oracdc-testa2|worker] Starting oracdc
'oracdc-testa2' logminer source connector
(eu.solutions.a2.cdc.oracle.OraCdcLogMinerConnector:61)
[2021-11-10 09:37:15,865] INFO [oracdc-testa2|worker]
OraCdcSourceConnectorConfig values:
a2.archived.log.catalog = eu.solutions.a2.cdc.oracle.OraCdcV$ArchivedLogImpl
a2.batch.size = 1000
a2.connection.backoff = 30000
a2.dictionary.file =
a2.distributed.activate = false
a2.distributed.target.host =
a2.distributed.target.port = 21521
a2.distributed.tns.admin =
a2.distributed.tns.alias =
a2.distributed.wallet.location =
a2.exclude = []
a2.fetch.size = 32
a2.first.change = 0
a2.include = [OT.%]
a2.initial.load = IGNORE
a2.jdbc.password = dbz
a2.jdbc.url = jdbc:oracle:thin:@//81.20.20.16 49154/ORCLCDB.localdomain
a2.jdbc.username = C##DBZUSER
a2.kafka.topic = oracle-cdc-claudio
a2.lob.transformation.class =
eu.solutions.a2.cdc.oracle.data.OraCdcDefaultLobTransformationsImpl
a2.logminer.trace = false
a2.oracdc.schemas = false
a2.persistent.state.file =
a2.poll.interval = 1000
a2.process.lobs = false
a2.redo.count = 1
a2.redo.size = 0
a2.schema.type = debezium
a2.standby.activate = false
a2.standby.tns.admin =
a2.standby.tns.alias =
a2.standby.wallet.location =
a2.table.list.style = static
a2.tmpdir =
a2.tns.admin =
a2.tns.alias =
a2.topic.name.delimiter = _
a2.topic.name.style = TABLE
a2.topic.prefix =
a2.wallet.location =
 (eu.solutions.a2.cdc.oracle.OraCdcSourceConnectorConfig:376)
[2021-11-10 09:37:15,868] INFO [oracdc-testa2|worker] Starting connection
to database jdbc:oracle:thin:@//81.20.20.16 49154/ORCLCDB.localdomain...
(eu.solutions.a2.cdc.oracle.OraPoolConnectionFactory:87)
[2021-11-10 09:37:15,922] ERROR [oracdc-testa2|worker]
WorkerConnector{id=oracdc-testa2} Error while starting connector
(org.apache.kafka.connect.runtime.WorkerConnector:192)
java.lang.ExceptionInInitializerError
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:398)
at
oracle.ucp.jdbc.PoolDataSourceImpl.initConnectionFactory(PoolDataSourceImpl.java:3237)
at
oracle.ucp.jdbc.PoolDataSourceImpl.createUniversalConnectionPool(PoolDataSourceImpl.java:1105)
at
oracle.ucp.admin.UniversalConnectionPoolManagerBase.createConnectionPool(UniversalConnectionPoolManagerBase.java:811)
at
eu.solutions.a2.cdc.oracle.OraPoolConnectionFactory.init(OraPoolConnectionFactory.java:110)
at
eu.solutions.a2.cdc.oracle.OraPoolConnectionFactory.init(OraPoolConnectionFactory.java:72)
at
eu.solutions.a2.cdc.oracle.OraCdcLogMinerConnector.start(OraCdcLogMinerConnector.java:68)
at
org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:184)
at
org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:209)
at
org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:348)
at
org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:331)
at
org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:140)
at
org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:117)
at
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.SecurityException: sealing violation: package
oracle.jdbc.driver is sealed
at
java.base/jdk.internal.loader.BuiltinClassLoader.getAndVerifyPackage(BuiltinClassLoader.java:844)
at
java.base/jdk.internal.loader.BuiltinClassLoader.defineOrCheckPackage(BuiltinClassLoader.java:815)
at
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.defineOrCheckPackage(ClassLoaders.java:211)
at
java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:787)
at
java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
at
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
at oracle.jdbc.pool.OracleDataSource.<clinit>(OracleDataSource.java:125)
... 19 more
[2021-11-10 09:37:17,274] ERROR [oracdc-testa2|worker] [Worker
clientId=connect-1, groupId=connect-cluster-group] Failed to start
connector 'oracdc-testa2'
(org.apache.kafka.connect.runtime.distributed.DistributedHerder:1490)
org.apache.kafka.connect.errors.ConnectException: Failed to start
connector: oracdc-testa2
at
org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$startConnector$25(DistributedHerder.java:1461)
at
org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:334)
at
org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:140)
at
org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:117)
at
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to
transition connector oracdc-testa2 to state STARTED
... 8 more
Caused by: java.lang.ExceptionInInitializerError
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:398)
at
oracle.ucp.jdbc.PoolDataSourceImpl.initConnectionFactory(PoolDataSourceImpl.java:3237)
at
oracle.ucp.jdbc.PoolDataSourceImpl.createUniversalConnectionPool(PoolDataSourceImpl.java:1105)
at
oracle.ucp.admin.UniversalConnectionPoolManagerBase.createConnectionPool(UniversalConnectionPoolManagerBase.java:811)
at
eu.solutions.a2.cdc.oracle.OraPoolConnectionFactory.init(OraPoolConnectionFactory.java:110)
at
eu.solutions.a2.cdc.oracle.OraPoolConnectionFactory.init(OraPoolConnectionFactory.java:72)
at
eu.solutions.a2.cdc.oracle.OraCdcLogMinerConnector.start(OraCdcLogMinerConnector.java:68)
at
org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:184)
at
org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:209)
at
org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:348)
at
org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:331)
... 7 more
Caused by: java.lang.SecurityException: sealing violation: package
oracle.jdbc.driver is sealed
at
java.base/jdk.internal.loader.BuiltinClassLoader.getAndVerifyPackage(BuiltinClassLoader.java:844)
at
java.base/jdk.internal.loader.BuiltinClassLoader.defineOrCheckPackage(BuiltinClassLoader.java:815)
at
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.defineOrCheckPackage(ClassLoaders.java:211)
at
java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:787)
at
java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
at
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
at
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
at oracle.jdbc.pool.OracleDataSource.<clinit>(OracleDataSource.java:125)
... 19 more

**Comment by averemee-si** [comment]
Hola Claudio,

Thanks for the update!
It's not networking issue, problem is in class loading: could you please send me full zipped connector.log to oracle@a2-solutions.eu

Thanks!

Regards,
Aleksei

**Comment by claudio-navarro-martinez** [comment]
attached

I can see in the logs:
sealing violation: package oracle.jdbc.driver is sealed

I put the ojdbc8.jar under:
/home/claudio/kafka.azure/kafka_2.12-3.0.0/logs# ls -lrt ../libs/ojdbc8*
-rw-r--r-- 1 root root 4210517 nov  8 12:03 ../libs/ojdbc8.jar
-rw-r--r-- 1 root root 4210517 nov  9 12:13 ../libs/ojdbc8-19.3.0.0.jar
-rw-r--r-- 1 root root 5056377 nov  9 13:17 ../libs/ojdbc8-21.3.0.0.jar

by the way, in which box runs the extraction of the redologs ? in the Azure
side or in my laptop where I trigger the connect-distributed.sh ?

thanks!!

**Comment by averemee-si** [comment]
Hola Claudio,

Thanks for the update!

**Comment by averemee-si** [comment]
Hola Claudio,

Regarding redo log extraction:

**Comment by claudio-navarro-martinez** [comment]
ok, it seems I missed an step. For installing your connector, I just download it, extracted it and copied the jat files under the lib subdirectory to the kafka/libs directory
that oracdc-kafka-0.9.8.3-standalone.jar file is not in the a2solutions-oracdc-kafka-0.9.8.3.zip file
so you saying I need to run maven? how?
thanks!!

**Comment by averemee-si** [comment]
Hola Claudio,

`a2solutions-oracdc-kafka-0.9.8.3.zip` is for [Confluent Platform](https://www.confluent.io/) distribution of Kafka. You can use it after unzipping and copying **all** jar files in lib directory to your libs.
Or you need to run
```
man install
```
for sources to produce single Uber-jar which includes all required dependencies.

Hope this helps.

Regards,
Aleksei
