### ISSUE TITLE
Error when doing mvn install

### ISSUE THREAD

**Issue by darklord1807** [averemee-si/oracdc#27]
Hello, 

Getting below error when compiling. Any help on same:

[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ oracdc-kafka ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ oracdc-kafka ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ oracdc-kafka ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/naveesh/Downloads/oracdc-0.9.9.2/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ oracdc-kafka ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ oracdc-kafka ---
[INFO] Surefire report directory: /Users/naveesh/Downloads/oracdc-0.9.9.2/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running eu.solutions.a2.cdc.oracle.OraCdcSinkSqlInsertTest
========== Oracle ========================
merge into DEPT D using
(select ? DEPTID,? DEPTNO,? DNAME,? LOC from DUAL) ORACDC
on (D.DEPTID=ORACDC.DEPTID and D.DEPTNO=ORACDC.DEPTNO)
when matched then update
set D.DNAME=ORACDC.DNAME,D.LOC=ORACDC.LOC
when not matched then
insert(DEPTID,DEPTNO,DNAME,LOC)
values(ORACDC.DEPTID,ORACDC.DEPTNO,ORACDC.DNAME,ORACDC.LOC)

update DEPT set DEPT_CODE_PDF=? where DEPTID=? and DEPTNO=?
========== PostgreSQL ====================
insert into DEPT(DEPTID,DEPTNO,DNAME,LOC) values(?,?,?,?) on conflict(DEPTID,DEPTNO) do update set DNAME=EXCLUDED.DNAME,LOC=EXCLUDED.LOC

update DEPT set DEPT_CODE_PDF=? where DEPTID=? and DEPTNO=?
========== MySQL ==========================
insert into DEPT(DEPTID,DEPTNO,DNAME,LOC) values(?,?,?,?) on duplicate key update DNAME=VALUES(DNAME),LOC=VALUES(LOC)

update DEPT set DEPT_CODE_PDF=? where DEPTID=? and DEPTNO=?
========== MsSQL ==========================
merge into DEPT D using
(select ? DEPTID,? DEPTNO,? DNAME,? LOC ) ORACDC
on (D.DEPTID=ORACDC.DEPTID and D.DEPTNO=ORACDC.DEPTNO)
when matched then update
set D.DNAME=ORACDC.DNAME,D.LOC=ORACDC.LOC
when not matched then
insert(DEPTID,DEPTNO,DNAME,LOC)
values(ORACDC.DEPTID,ORACDC.DEPTNO,ORACDC.DNAME,ORACDC.LOC);

update DEPT set DEPT_CODE_PDF=? where DEPTID=? and DEPTNO=?
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.082 sec
Running eu.solutions.a2.cdc.oracle.OraDumpDecoderTest
thanks
謝謝啦
Σας ευχαριστώ
Спасибо
2020-02-04 13:59:23.0
-0.1828
-0.1828
-0.1828
1.7320508
1.7320508075688772
1.7320508
1.7320508
1.7320508
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.027 sec
Running eu.solutions.a2.cdc.oracle.OraCdcChronicleQueueTest
log4j:WARN No appenders could be found for logger (eu.solutions.a2.cdc.oracle.OraCdcTransaction).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.206 sec <<< FAILURE!
test(eu.solutions.a2.cdc.oracle.OraCdcChronicleQueueTest)  Time elapsed: 0.206 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
	at net.openhft.chronicle.core.Jvm.getSetAccessible0Method(Jvm.java:233)
	at net.openhft.chronicle.core.Jvm.<clinit>(Jvm.java:140)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.loadDefaultRollCycle(SingleChronicleQueueBuilder.java:274)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.rollCycle(SingleChronicleQueueBuilder.java:746)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.initializeMetadata(SingleChronicleQueueBuilder.java:442)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.preBuild(SingleChronicleQueueBuilder.java:1083)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:323)
	at eu.solutions.a2.cdc.oracle.OraCdcTransaction.<init>(OraCdcTransaction.java:86)
	at eu.solutions.a2.cdc.oracle.OraCdcTransaction.<init>(OraCdcTransaction.java:118)
	at eu.solutions.a2.cdc.oracle.OraCdcChronicleQueueTest.test(OraCdcChronicleQueueTest.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.openhft.chronicle.core.Jvm.getSetAccessible0Method(Jvm.java:230)
	... 41 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @32816a91
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:259)
	... 46 more

Running eu.solutions.a2.cdc.oracle.OraCdcPersistenceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
test(eu.solutions.a2.cdc.oracle.OraCdcPersistenceTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class net.openhft.chronicle.core.Jvm
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.loadDefaultRollCycle(SingleChronicleQueueBuilder.java:274)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.rollCycle(SingleChronicleQueueBuilder.java:746)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.initializeMetadata(SingleChronicleQueueBuilder.java:442)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.preBuild(SingleChronicleQueueBuilder.java:1083)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:323)
	at eu.solutions.a2.cdc.oracle.OraCdcTransaction.<init>(OraCdcTransaction.java:86)
	at eu.solutions.a2.cdc.oracle.OraCdcTransaction.<init>(OraCdcTransaction.java:118)
	at eu.solutions.a2.cdc.oracle.OraCdcPersistenceTest.test(OraCdcPersistenceTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running eu.solutions.a2.cdc.oracle.OraCdcTransformNestedSchemaTest
++++++++++ Oracle ++++++++++++++++++++++++
create table FND_LOBS(
  FILE_ID NUMBER(19) not null,
  FILE_NAME VARCHAR2(4000),
  FILE_CONTENT_TYPE VARCHAR2(4000) not null,
  S3_URL VARCHAR2(4000),
  constraint FND_LOBS_PK primary key(FILE_ID)
)
++++++++++ PostgreSQL +++++++++++++++++++++
create table FND_LOBS(
  FILE_ID bigint not null,
  FILE_NAME text,
  FILE_CONTENT_TYPE text not null,
  S3_URL text,
  constraint FND_LOBS_PK primary key(FILE_ID)
)
++++++++++ MySQL ++++++++++++++++++++++++++
create table FND_LOBS(
  FILE_ID bigint not null,
  FILE_NAME varchar(255),
  FILE_CONTENT_TYPE varchar(255) not null,
  S3_URL varchar(255),
  constraint FND_LOBS_PK primary key(FILE_ID)
)
++++++++++ MsSQL ++++++++++++++++++++++++++
create table FND_LOBS(
  FILE_ID bigint not null,
  FILE_NAME nvarchar(4000),
  FILE_CONTENT_TYPE nvarchar(4000) not null,
  S3_URL nvarchar(4000),
  constraint FND_LOBS_PK primary key(FILE_ID)
)
========== Oracle ========================
merge into FND_LOBS D using
(select ? FILE_ID,? FILE_NAME,? FILE_CONTENT_TYPE from DUAL) ORACDC
on (D.FILE_ID=ORACDC.FILE_ID)
when matched then update
set D.FILE_NAME=ORACDC.FILE_NAME,D.FILE_CONTENT_TYPE=ORACDC.FILE_CONTENT_TYPE
when not matched then
insert(FILE_ID,FILE_NAME,FILE_CONTENT_TYPE)
values(ORACDC.FILE_ID,ORACDC.FILE_NAME,ORACDC.FILE_CONTENT_TYPE)

update FND_LOBS set S3_URL=? where FILE_ID=?
========== PostgreSQL ====================
insert into FND_LOBS(FILE_ID,FILE_NAME,FILE_CONTENT_TYPE) values(?,?,?) on conflict(FILE_ID) do update set FILE_NAME=EXCLUDED.FILE_NAME,FILE_CONTENT_TYPE=EXCLUDED.FILE_CONTENT_TYPE

update FND_LOBS set S3_URL=? where FILE_ID=?
========== MySQL ==========================
insert into FND_LOBS(FILE_ID,FILE_NAME,FILE_CONTENT_TYPE) values(?,?,?) on duplicate key update FILE_NAME=VALUES(FILE_NAME),FILE_CONTENT_TYPE=VALUES(FILE_CONTENT_TYPE)

update FND_LOBS set S3_URL=? where FILE_ID=?
========== MsSQL ==========================
merge into FND_LOBS D using
(select ? FILE_ID,? FILE_NAME,? FILE_CONTENT_TYPE ) ORACDC
on (D.FILE_ID=ORACDC.FILE_ID)
when matched then update
set D.FILE_NAME=ORACDC.FILE_NAME,D.FILE_CONTENT_TYPE=ORACDC.FILE_CONTENT_TYPE
when not matched then
insert(FILE_ID,FILE_NAME,FILE_CONTENT_TYPE)
values(ORACDC.FILE_ID,ORACDC.FILE_NAME,ORACDC.FILE_CONTENT_TYPE);

update FND_LOBS set S3_URL=? where FILE_ID=?
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec
Running eu.solutions.a2.cdc.oracle.OraCdcCQLobPersistenceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 sec <<< FAILURE!
test(eu.solutions.a2.cdc.oracle.OraCdcCQLobPersistenceTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class net.openhft.chronicle.core.Jvm
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.loadDefaultRollCycle(SingleChronicleQueueBuilder.java:274)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.rollCycle(SingleChronicleQueueBuilder.java:746)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.initializeMetadata(SingleChronicleQueueBuilder.java:442)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.preBuild(SingleChronicleQueueBuilder.java:1083)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:323)
	at eu.solutions.a2.cdc.oracle.OraCdcTransaction.<init>(OraCdcTransaction.java:86)
	at eu.solutions.a2.cdc.oracle.OraCdcCQLobPersistenceTest.processQueueBeforeRestart(OraCdcCQLobPersistenceTest.java:70)
	at eu.solutions.a2.cdc.oracle.OraCdcCQLobPersistenceTest.test(OraCdcCQLobPersistenceTest.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running eu.solutions.a2.cdc.oracle.OraCdcSinkCreateTableTest
++++++++++ Oracle ++++++++++++++++++++++++
create table DEPT(
  DEPTNO NUMBER(3) not null,
  DNAME VARCHAR2(4000),
  LOC VARCHAR2(4000),
  DEPT_CODE_PDF BLOB,
  DEPT_CODE_DOCX BLOB,
  DEPT_CODE_XML XMLTYPE,
  constraint DEPT_PK primary key(DEPTNO)
)
++++++++++ PostgreSQL +++++++++++++++++++++
create table DEPT(
  DEPTNO smallint not null,
  DNAME text,
  LOC text,
  DEPT_CODE_PDF lo,
  DEPT_CODE_DOCX lo,
  DEPT_CODE_XML text,
  constraint DEPT_PK primary key(DEPTNO)
)
	CREATE TRIGGER t_lo_DEPT_DEPT_CODE_PDF BEFORE UPDATE OR DELETE ON DEPT
	FOR EACH ROW EXECUTE FUNCTION lo_manage(DEPT_CODE_PDF)

	CREATE TRIGGER t_lo_DEPT_DEPT_CODE_DOCX BEFORE UPDATE OR DELETE ON DEPT
	FOR EACH ROW EXECUTE FUNCTION lo_manage(DEPT_CODE_DOCX)

++++++++++ MySQL ++++++++++++++++++++++++++
create table DEPT(
  DEPTNO tinyint not null,
  DNAME varchar(255),
  LOC varchar(255),
  DEPT_CODE_PDF longblob,
  DEPT_CODE_DOCX longblob,
  DEPT_CODE_XML longtext,
  constraint DEPT_PK primary key(DEPTNO)
)
++++++++++ MsSQL ++++++++++++++++++++++++++
create table DEPT(
  DEPTNO tinyint not null,
  DNAME nvarchar(4000),
  LOC nvarchar(4000),
  DEPT_CODE_PDF varbinary(max),
  DEPT_CODE_DOCX varbinary(max),
  DEPT_CODE_XML xml,
  constraint DEPT_PK primary key(DEPTNO)
)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running eu.solutions.a2.cdc.oracle.OraNumberTest
eu.solutions.a2.cdc.oracle.data.OraNumber
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running eu.solutions.a2.cdc.oracle.OraCdcAlterTablePreProcessorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec
Running eu.solutions.a2.cdc.oracle.OraCdcParseTableSchemaListTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running eu.solutions.a2.cdc.oracle.OraCdcCQPersistenceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
test(eu.solutions.a2.cdc.oracle.OraCdcCQPersistenceTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class net.openhft.chronicle.core.Jvm
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.loadDefaultRollCycle(SingleChronicleQueueBuilder.java:274)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.rollCycle(SingleChronicleQueueBuilder.java:746)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.initializeMetadata(SingleChronicleQueueBuilder.java:442)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.preBuild(SingleChronicleQueueBuilder.java:1083)
	at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:323)
	at eu.solutions.a2.cdc.oracle.OraCdcTransaction.<init>(OraCdcTransaction.java:86)
	at eu.solutions.a2.cdc.oracle.OraCdcTransaction.<init>(OraCdcTransaction.java:118)
	at eu.solutions.a2.cdc.oracle.OraCdcCQPersistenceTest.processQueueBeforeRestart(OraCdcCQPersistenceTest.java:58)
	at eu.solutions.a2.cdc.oracle.OraCdcCQPersistenceTest.test(OraCdcCQPersistenceTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by averemee-si** [comment]
Looks like [Can't work with JDK17](https://github.com/OpenHFT/Chronicle-Queue/issues/909) for Chronicle

**Comment by averemee-si** [comment]
Hello,

Which java version you are using?
i.e. output of
```
java -version
```

Thanks!
Aleksei

**Comment by darklord1807** [comment]
Was able to make it work through IDE. Thanks for the help.

Is it possible to use the library without Kafka Connect? I want to push the
Oracle CDC directly to a Kafka topic without Kafka Connect.

Thanks,
Naveesh

**Comment by averemee-si** [comment]
Hi Naveesh,

Unfortunately current implementation is for Kafka Connect.
I will check the possibility of working without a Kafka Connect.

Best regards,
Aleksei

**Comment by averemee-si** [comment]
Fixed in v1.0.0
