### ISSUE TITLE
SQLException: Overflow Exception

### ISSUE THREAD

**Issue by amticianelli** [averemee-si/oracdc#29]
Hi Aleksei, 

we are facing an error when trying to send tables with a high precision:

```shell
java.sql.SQLException: java.sql.SQLException: java.sql.SQLException: Invalid Oracle NUMBER
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecord(OraTable4LogMiner.java:422)
	at solutions.a2.cdc.oracle.OraCdcLogMinerTask.poll(OraCdcLogMinerTask.java:894)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:305)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:249)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: java.sql.SQLException: Invalid Oracle NUMBER
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecordValues(OraTable4LogMiner.java:849)
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecord(OraTable4LogMiner.java:416)
	... 10 more
Caused by: java.sql.SQLException: Invalid Oracle NUMBER
	at solutions.a2.cdc.oracle.OraDumpDecoder.toInt(OraDumpDecoder.java:83)
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecordValues(OraTable4LogMiner.java:736)
	... 11 more
Caused by: java.sql.SQLException: Overflow Exception
	at oracle.sql.NUMBER.toLongInternal(NUMBER.java:465)
	at oracle.sql.NUMBER.toInt(NUMBER.java:489)
	at solutions.a2.cdc.oracle.OraDumpDecoder.toInt(OraDumpDecoder.java:81)
	... 12 more
```

Here is the table DDL:
```sql
CREATE TABLE "****"."****" 
   (	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A', 
	"AMND_OFFICER" NUMBER(18,0), 
	"AMND_DATE" DATE DEFAULT sysdate, 
	"AMND_PREV" NUMBER(18,0), 
	"ID" NUMBER(18,0) NOT NULL ENABLE, 
	"DOC__ORIG__ID" NUMBER(18,0), 
	"DOC__PREV__ID" NUMBER(18,0), 
	"DOC__SUMM__ID" NUMBER(18,0), 
	"NUMBER_OF_SUB_S" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE, 
	"ACTION" VARCHAR2(1 CHAR), 
	"MESSAGE_CATEGORY" VARCHAR2(1 CHAR), 
	"SOURCE_REG_NUM" VARCHAR2(32 CHAR), 
	"ACQ_REF_NUMBER" VARCHAR2(32 CHAR), 
	"RET_REF_NUMBER" VARCHAR2(12 CHAR), 
	"ISS_REF_NUMBER" VARCHAR2(32 CHAR), 
	"PS_REF_NUMBER" VARCHAR2(255 CHAR), 
	"NW_REF_DATE" DATE, 
	"AUTH_CODE" VARCHAR2(32 CHAR), 
	"IS_AUTHORIZATION" VARCHAR2(1 CHAR), 
	"REQUEST_CATEGORY" VARCHAR2(1 CHAR), 
	"SERVICE_CLASS" VARCHAR2(1 CHAR), 
	"SOURCE_CODE" VARCHAR2(32 CHAR), 
	"SOURCE_FEE_CODE" VARCHAR2(32 CHAR), 
	"TARGET_CODE" VARCHAR2(32 CHAR), 
	"TARGET_FEE_CODE" VARCHAR2(32 CHAR), 
	"TRANS_TYPE" NUMBER(18,0), 
	"SOURCE_CHANNEL" VARCHAR2(32 CHAR), 
	"S_CAT" VARCHAR2(1 CHAR), 
	"SOURCE_IDT_SCHEME" VARCHAR2(32 CHAR), 
	"SOURCE_MEMBER_ID" VARCHAR2(32 CHAR), 
	"REC_MEMBER_ID" VARCHAR2(32 CHAR), 
	"SOURCE_NUMBER" VARCHAR2(64 CHAR) ENCRYPT USING 'AES192' 'NOMAC' NO SALT , 
	"SOURCE_SPC" VARCHAR2(32 CHAR), 
	"SOURCE_ACC_TYPE" VARCHAR2(32 CHAR), 
	"SOURCE_CONTRACT" NUMBER(18,0), 
	"SOURCE_SERVICE" NUMBER(18,0), 
	"TARGET_CHANNEL" VARCHAR2(32 CHAR), 
	"T_CAT" VARCHAR2(1 CHAR), 
	"TARGET_IDT_SCHEME" VARCHAR2(32 CHAR), 
	"TARGET_MEMBER_ID" VARCHAR2(32 CHAR), 
	"SEND_MEMBER_ID" VARCHAR2(32 CHAR), 
	"SENDING_BIN" VARCHAR2(32 CHAR), 
	"TARGET_BIN_ID" NUMBER(18,0), 
	"TARGET_NUMBER" VARCHAR2(64 CHAR) ENCRYPT USING 'AES192' 'NOMAC' NO SALT , 
	"TARGET_SPC" VARCHAR2(32 CHAR), 
	"TARGET_ACC_TYPE" VARCHAR2(32 CHAR), 
	"TARGET_CONTRACT" NUMBER(18,0), 
	"TARGET_SERVICE" NUMBER(18,0), 
	"CARD_EXPIRE" VARCHAR2(4 CHAR), 
	"CARD_SEQV_NUMBER" VARCHAR2(32 CHAR), 
	"MERCHANT_ID" VARCHAR2(32 CHAR), 
	"SIC_CODE" VARCHAR2(4 CHAR), 
	"TRANS_CONDITION" VARCHAR2(32 CHAR), 
	"TRANS_COND_ATTR" NUMBER(18,0), 
	"SEC_TRANS_COND_ATT" NUMBER(18,0), 
	"RECONS_CURR" VARCHAR2(3 CHAR), 
	"RECONS_AMOUNT" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE, 
	"SETTL_CURR" VARCHAR2(3 CHAR), 
	"SETTL_AMOUNT" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE, 
	"SOURCE_FEE_CURR" VARCHAR2(3 CHAR), 
	"SOURCE_FEE_AMOUNT" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE, 
	"TARGET_FEE_CURR" VARCHAR2(3 CHAR), 
	"TARGET_FEE_AMOUNT" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE, 
	"TRANS_DATE" DATE DEFAULT sysdate, 
	"SEC_TRANS_DATE" DATE, 
	"TRANS_COUNTRY" VARCHAR2(3 CHAR), 
	"TRANS_STATE" VARCHAR2(32 CHAR), 
	"TRANS_CITY" VARCHAR2(32 CHAR), 
	"TRANS_DETAILS" VARCHAR2(255 CHAR), 
	"TRANS_AMOUNT" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE, 
	"TRANS_CURR" VARCHAR2(3 CHAR), 
	"REASON_CODE" VARCHAR2(32 CHAR), 
	"REASON_DETAILS" VARCHAR2(3900 CHAR), 
	"REQUIREMENT" VARCHAR2(4 CHAR), 
	"POSTING_DATE" DATE, 
	"FX_SETTL_DATE" DATE, 
	"POSTING_STATUS" VARCHAR2(1 CHAR), 
	"OUTWARD_STATUS" VARCHAR2(1 CHAR) DEFAULT 'W', 
	"RETURN_CODE" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE, 
	"PARTITION_KEY" VARCHAR2(32 CHAR) DEFAULT 'X', 
	"SYNCH_TAG" VARCHAR2(1 CHAR), 
	"BIN_RECORD" NUMBER(18,0), 
	"NUMBER_IN_CHAIN" NUMBER(9,0), 
	"ADD_INFO" VARCHAR2(3900 CHAR) ENCRYPT USING 'AES192' 'NOMAC' NO SALT , 
	"CHANGE_VERSION" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE, 
	"TARGET_COUNTRY" VARCHAR2(3 CHAR), 
	"REC_DATE" DATE DEFAULT sysdate, 
	"COMMENT_TEXT" VARCHAR2(3900 CHAR), 
	"DOC__CHAIN__ID" NUMBER(18,0), 
	 CONSTRAINT "PK_DOC" PRIMARY KEY ("ID")
)
```

Is there some way to convert this big NUMBER to another type so we can send this table to Kafka?

Thanks in advance!

Alberto.

**Comment by averemee-si** [comment]
Salve Alberto,

This should generate in connect.log additional debug information.
You can find it using

```
grep "While decoding redo values for table" connect.log
```

Please update this issue with this debug.

In addition could you please provide:

```
select max(NUMBER_OF_SUB_S), max(RETURN_CODE), max(NUMBER_IN_CHAIN), max(CHANGE_VERSION)
from <PROBLEM_TABLE>
```

Thanks!

Best regards,
Aleksei

**Comment by amticianelli** [comment]
Aleksei, here it is:

```shell
2022-07-29 12:54:24,902 ERROR [oracdc-source-016|task-0] Invalid Oracle NUMBER! While decoding redo values for table OWS.DOC
		column CHANGE_VERSION
		JDBC Type INTEGER
		dump value (hex) '371e6d20a179096002f06dd3c23f2dcd267e9df2768cfa2c309102f225c246a2cbafd53e048e8aacaeb4a09b46ae8f75859bd38dd119512de92958b0afcfcb710b251a7907495d179f715d49b5a940c47ae3dd7d3295b0bef6b507e34cd479c896730e43938882f06960930476a6f857ae3c72234d971202d28bf748aa0f0a38a337be26573b6de3fae0ac79761770684ab613efc56c164eea3fd706e46e33f930621a55b78a6611f993899e1db7d3df59f6ec6322714d2e985e0cd71014136671697a2a286966043c39eaa0691bd826fc4c14b764e8655560d50f0b665cd32c7769ee11f2f00444f4b6fcca649d6df2bc8d9a2ca67452dff5149254db56144d1d057d8c2d7ecb165cfdcb263e5e5a5a804cd08310352c40ba4363305c05ce67da430eac0791215be19de0f727d3efb01368d0e4a8d6c6006488f3b90e0516889589e1bdc66f1d37bc99d48001e704e03ead64f397056009510d698fdbfabb8804ad6e1bb9b40ad4e75ae93ad1c79a293d950ec95a831a16fb9ee3e06e1d06b44ce0cbec35883aa5f27798f3e0f3b738e8e18cc7981f7f7d920311ce45731645c3bfedf82751c0e6aafa9912d9bbb2038789192632b97f1f056de3434bd76b384954a11a7daedcac8ca805e9dec78b7c1e4bf9502f6e66317ce50c24016c09337ced05a8c777df199993804eb01c41bdc7b1aaf9b99ba97dab85936af33c1cfcc3b3da15821f0f9bbf222e39d1c14302' (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] Invalid value '371e6d20a179096002f06dd3c23f2dcd267e9df2768cfa2c309102f225c246a2cbafd53e048e8aacaeb4a09b46ae8f75859bd38dd119512de92958b0afcfcb710b251a7907495d179f715d49b5a940c47ae3dd7d3295b0bef6b507e34cd479c896730e43938882f06960930476a6f857ae3c72234d971202d28bf748aa0f0a38a337be26573b6de3fae0ac79761770684ab613efc56c164eea3fd706e46e33f930621a55b78a6611f993899e1db7d3df59f6ec6322714d2e985e0cd71014136671697a2a286966043c39eaa0691bd826fc4c14b764e8655560d50f0b665cd32c7769ee11f2f00444f4b6fcca649d6df2bc8d9a2ca67452dff5149254db56144d1d057d8c2d7ecb165cfdcb263e5e5a5a804cd08310352c40ba4363305c05ce67da430eac0791215be19de0f727d3efb01368d0e4a8d6c6006488f3b90e0516889589e1bdc66f1d37bc99d48001e704e03ead64f397056009510d698fdbfabb8804ad6e1bb9b40ad4e75ae93ad1c79a293d950ec95a831a16fb9ee3e06e1d06b44ce0cbec35883aa5f27798f3e0f3b738e8e18cc7981f7f7d920311ce45731645c3bfedf82751c0e6aafa9912d9bbb2038789192632b97f1f056de3434bd76b384954a11a7daedcac8ca805e9dec78b7c1e4bf9502f6e66317ce50c24016c09337ced05a8c777df199993804eb01c41bdc7b1aaf9b99ba97dab85936af33c1cfcc3b3da15821f0f9bbf222e39d1c14302' for column CHANGE_VERSION in table OWS.DOC (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] NULL value for NON NULL column CHANGE_VERSION, table OWS.DOC (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] Redo record information for table OWS.DOC: (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] 	SCN = 82207671290 (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] 	COMMIT_SCN = 82207671322 (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] 	XID = 0028000700161AF1 (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] 	TIMESTAMP = 1659019927000 (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] 	RS_ID =  0x021505.0000b4fe.0090  (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] 	SSN = 3 (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] 	ROW_ID = AAA/tbAGxAACAtfAAD (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] 	OPERATION_CODE = 1 (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,903 ERROR [oracdc-source-016|task-0] 	SQL_REDO = insert into "UNKNOWN"."OBJ# 260955"("COL 1","COL 2","COL 3","COL 4","COL 5","COL 6","COL 7","COL 8","COL 9","COL 10","COL 11","COL 12","COL 13","COL 14","COL 15","COL 16","COL 17","COL 18","COL 19","COL 20","COL 21","COL 22","COL 23","COL 24","COL 25","COL 26","COL 27","COL 28","COL 29","COL 30","COL 31","COL 32","COL 33","COL 34","COL 35","COL 36","COL 37","COL 38","COL 39","COL 40","COL 41","COL 42","COL 43","COL 44","COL 45","COL 46","COL 47","COL 48","COL 49","COL 50","COL 51","COL 52","COL 53","COL 54","COL 55","COL 56","COL 57","COL 58","COL 59","COL 60","COL 61","COL 62","COL 63","COL 64","COL 65","COL 66","COL 67","COL 68","COL 69","COL 70","COL 71","COL 72","COL 73","COL 74","COL 75","COL 76","COL 77","COL 78","COL 79","COL 80","COL 81","COL 82","COL 83","COL 84","COL 85","COL 86","COL 87","COL 88") values ('41','c3022d','787a071c0f3506','c602190e5c4b51','c602190e5c4b51',NULL,NULL,NULL,'80',NULL,NULL,'4d323039313134554c394951',NULL,'323230393231303030303333','33393433383734363030303033333637393939395f5f5f5f5f5f5f5f5f303036',NULL,'787a071c0f3505',NULL,'4e','50','54',NULL,NULL,NULL,NULL,'c106','50','4d',NULL,'37303031',NULL,'b9697863b68a4be2bdc2334b82ec9ec4',NULL,NULL,'c4043b3e1f','c504274c2c3d','45','43',NULL,'3831303030303030','303035333032','353435333032',NULL,'e0464922159beaf8a28933c3d6f2afa5ad0ffb18f5f8e012970ea909a9aaff28','3030',NULL,'c342033d','c5041f3f150b','32353132','3235','39313230333730','30373432','504f534c','c30a171f',NULL,'393738','c10d','393738','c10d',NULL,'80',NULL,'80','787a071c103504',NULL,'474252',NULL,'536f6d652043697479','53746f7265204e616d65','c10d','393738',NULL,NULL,NULL,NULL,NULL,'53','57','80',NULL,'58',NULL,'c3085717','80','371e6d20a179096002f06dd3c23f2dcd267e9df2768cfa2c309102f225c246a2cbafd53e048e8aacaeb4a09b46ae8f75859bd38dd119512de92958b0afcfcb710b251a7907495d179f715d49b5a940c47ae3dd7d3295b0bef6b507e34cd479c896730e43938882f06960930476a6f857ae3c72234d971202d28bf748aa0f0a38a337be26573b6de3fae0ac79761770684ab613efc56c164eea3fd706e46e33f930621a55b78a6611f993899e1db7d3df59f6ec6322714d2e985e0cd71014136671697a2a286966043c39eaa0691bd826fc4c14b764e8655560d50f0b665cd32c7769ee11f2f00444f4b6fcca649d6df2bc8d9a2ca67452dff5149254db56144d1d057d8c2d7ecb165cfdcb263e5e5a5a804cd08310352c40ba4363305c05ce67da430eac0791215be19de0f727d3efb01368d0e4a8d6c6006488f3b90e0516889589e1bdc66f1d37bc99d48001e704e03ead64f397056009510d698fdbfabb8804ad6e1bb9b40ad4e75ae93ad1c79a293d950ec95a831a16fb9ee3e06e1d06b44ce0cbec35883aa5f27798f3e0f3b738e8e18cc7981f7f7d920311ce45731645c3bfedf82751c0e6aafa9912d9bbb2038789192632b97f1f056de3434bd76b384954a11a7daedcac8ca805e9dec78b7c1e4bf9502f6e66317ce50c24016c09337ced05a8c777df199993804eb01c41bdc7b1aaf9b99ba97dab85936af33c1cfcc3b3da15821f0f9bbf222e39d1c14302','80','49534c','787a071c0f3507') (solutions.a2.cdc.oracle.OraTable4LogMiner) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,905 ERROR [oracdc-source-016|task-0] java.sql.SQLException: java.sql.SQLException: Invalid Oracle NUMBER (solutions.a2.cdc.oracle.OraCdcLogMinerTask) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,911 ERROR [oracdc-source-016|task-0] java.sql.SQLException: java.sql.SQLException: Invalid Oracle NUMBER
java.sql.SQLException: java.sql.SQLException: java.sql.SQLException: Invalid Oracle NUMBER
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecord(OraTable4LogMiner.java:422)
	at solutions.a2.cdc.oracle.OraCdcLogMinerTask.poll(OraCdcLogMinerTask.java:894)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:305)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:249)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: java.sql.SQLException: Invalid Oracle NUMBER
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecordValues(OraTable4LogMiner.java:849)
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecord(OraTable4LogMiner.java:416)
	... 10 more
Caused by: java.sql.SQLException: Invalid Oracle NUMBER
	at solutions.a2.cdc.oracle.OraDumpDecoder.toInt(OraDumpDecoder.java:83)
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecordValues(OraTable4LogMiner.java:736)
	... 11 more
Caused by: java.sql.SQLException: Overflow Exception
	at oracle.sql.NUMBER.toLongInternal(NUMBER.java:465)
	at oracle.sql.NUMBER.toInt(NUMBER.java:489)
	at solutions.a2.cdc.oracle.OraDumpDecoder.toInt(OraDumpDecoder.java:81)
	... 12 more
 (solutions.a2.cdc.oracle.OraCdcLogMinerTask) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,912 ERROR [oracdc-source-016|task-0] WorkerSourceTask{id=oracdc-source-016-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-oracdc-source-016-0]
org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: java.sql.SQLException: java.sql.SQLException: Invalid Oracle NUMBER
	at solutions.a2.cdc.oracle.OraCdcLogMinerTask.poll(OraCdcLogMinerTask.java:908)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:305)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:249)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: java.sql.SQLException: java.sql.SQLException: Invalid Oracle NUMBER
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecord(OraTable4LogMiner.java:422)
	at solutions.a2.cdc.oracle.OraCdcLogMinerTask.poll(OraCdcLogMinerTask.java:894)
	... 9 more
Caused by: java.sql.SQLException: java.sql.SQLException: Invalid Oracle NUMBER
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecordValues(OraTable4LogMiner.java:849)
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecord(OraTable4LogMiner.java:416)
	... 10 more
Caused by: java.sql.SQLException: Invalid Oracle NUMBER
	at solutions.a2.cdc.oracle.OraDumpDecoder.toInt(OraDumpDecoder.java:83)
	at solutions.a2.cdc.oracle.OraTable4LogMiner.parseRedoRecordValues(OraTable4LogMiner.java:736)
	... 11 more
Caused by: java.sql.SQLException: Overflow Exception
	at oracle.sql.NUMBER.toLongInternal(NUMBER.java:465)
	at oracle.sql.NUMBER.toInt(NUMBER.java:489)
	at solutions.a2.cdc.oracle.OraDumpDecoder.toInt(OraDumpDecoder.java:81)
	... 12 more
2022-07-29 12:54:24,913 INFO [oracdc-source-016|task-0] Stopping oracdc logminer source task. (solutions.a2.cdc.oracle.OraCdcLogMinerTask) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,913 INFO [oracdc-source-016|task-0] Stopping oracdc logminer archivelog worker thread... (solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread) [task-thread-oracdc-source-016-0]
2022-07-29 12:54:24,977 INFO [oracdc-source-016|task-0] END: OraCdcLogMinerWorkerThread.run() (solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread) [OraCdcLogMinerWorkerThread-165193463723368]
2022-07-29 12:54:25,214 INFO [oracdc-source-016|task-0] [Producer clientId=connector-producer-oracdc-source-016-0] Closing the Kafka producer with timeoutMillis = 30000 ms. (org.apache.kafka.clients.producer.KafkaProducer) [task-thread-ora
```

It will take a while to return the result of the query you sent, I will be editing this post once its done.

**Comment by averemee-si** [comment]
Thanks!

Problem is in CHANGE_VERSION column.
According to data dictionary - this is NUMBER(9) which is mapped by default to Java int with 

```
jshell> Integer.MAX_VALUE
$1 ==> 2147483647
```

But 

```
371e6d20a179096002f06dd3c23f2dcd267e9df2768cfa2c309102f225c246a2cbafd53e048e8aacaeb4a09b46ae8f75859bd38dd119512de92958b0afcfcb710b251a7907495d179f715d49b5a940c47ae3dd7d3295b0bef6b507e34cd479c896730e43938882f06960930476a6f857ae3c72234d971202d28bf748aa0f0a38a337be26573b6de3fae0ac79761770684ab613efc56c164eea3fd706e46e33f930621a55b78a6611f993899e1db7d3df59f6ec6322714d2e985e0cd71014136671697a2a286966043c39eaa0691bd826fc4c14b764e8655560d50f0b665cd32c7769ee11f2f00444f4b6fcca649d6df2bc8d9a2ca67452dff5149254db56144d1d057d8c2d7ecb165cfdcb263e5e5a5a804cd08310352c40ba4363305c05ce67da430eac0791215be19de0f727d3efb01368d0e4a8d6c6006488f3b90e0516889589e1bdc66f1d37bc99d48001e704e03ead64f397056009510d698fdbfabb8804ad6e1bb9b40ad4e75ae93ad1c79a293d950ec95a831a16fb9ee3e06e1d06b44ce0cbec35883aa5f27798f3e0f3b738e8e18cc7981f7f7d920311ce45731645c3bfedf82751c0e6aafa9912d9bbb2038789192632b97f1f056de3434bd76b384954a11a7daedcac8ca805e9dec78b7c1e4bf9502f6e66317ce50c24016c09337ced05a8c777df199993804eb01c41bdc7b1aaf9b99ba97dab85936af33c1cfcc3b3da15821f0f9bbf222e39d1c14302
```
is too huge!!!
Looks like this database has long history of upgrades and some data are in contradiction with data dictionary information about it.

Thinking about this.

Please also run

```
select main(CHANGE_VERSION), max(CHANGE_VERSION), avg(CHANGE_VERSION)
from <PROBLEM_TABLE>
```

Thanks!

Best regards,
Aleksei

**Comment by averemee-si** [comment]
Salve Alberto,

I've made test case:

```
import oracle.sql.NUMBER;

	public static byte[] toByteArray(String hex) {
		int len = hex.length();
		byte[] data = new byte[len / 2];
		for (int i = 0; i < len; i += 2) {
			data[i / 2] = (byte) ((Character.digit(hex.charAt(i), 16) << 4) +
									Character.digit(hex.charAt(i+1), 16));
		}
		return data;
	}

	public static void main(String[] argv) {
		String bad = "371e6d20a179096002f06dd3c23f2dcd267e9df2768cfa2c309102f225c246a2cbafd53e048e8aacaeb4a09b46ae8f75859bd38dd119512de92958b0afcfcb710b251a7907495d179f715d49b5a940c47ae3dd7d3295b0bef6b507e34cd479c896730e43938882f06960930476a6f857ae3c72234d971202d28bf748aa0f0a38a337be26573b6de3fae0ac79761770684ab613efc56c164eea3fd706e46e33f930621a55b78a6611f993899e1db7d3df59f6ec6322714d2e985e0cd71014136671697a2a286966043c39eaa0691bd826fc4c14b764e8655560d50f0b665cd32c7769ee11f2f00444f4b6fcca649d6df2bc8d9a2ca67452dff5149254db56144d1d057d8c2d7ecb165cfdcb263e5e5a5a804cd08310352c40ba4363305c05ce67da430eac0791215be19de0f727d3efb01368d0e4a8d6c6006488f3b90e0516889589e1bdc66f1d37bc99d48001e704e03ead64f397056009510d698fdbfabb8804ad6e1bb9b40ad4e75ae93ad1c79a293d950ec95a831a16fb9ee3e06e1d06b44ce0cbec35883aa5f27798f3e0f3b738e8e18cc7981f7f7d920311ce45731645c3bfedf82751c0e6aafa9912d9bbb2038789192632b97f1f056de3434bd76b384954a11a7daedcac8ca805e9dec78b7c1e4bf9502f6e66317ce50c24016c09337ced05a8c777df199993804eb01c41bdc7b1aaf9b99ba97dab85936af33c1cfcc3b3da15821f0f9bbf222e39d1c14302";
		System.out.println("=" + NUMBER.toDouble(toByteArray(bad)));
		System.out.println("OK");
	}


```

And result is:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -14 out of bounds for length 102
	at oracle.sql.LnxLibThin.lnxnuc(LnxLibThin.java:5809)
	at oracle.sql.NUMBER.toDouble(NUMBER.java:405)
	at solutions.a2.cdc.oracle.OraDumpDecoder.main(OraDumpDecoder.java:89)
```

This means that Oracle JDBC is unable to parse these data.
You can find more information about Oracle's internal NUMBER format at https://support.oracle.com/rs?type=doc&id=1031902.6, https://www.orafaq.com/wiki/Number, https://gotodba.com/2015/03/24/how-are-numbers-saved-in-oracle/, https://docs.oracle.com/en/database/oracle/oracle-database/12.2/jajdb/index.html?oracle/sql/NUMBER.html

Now is better to produce dump of redo record and check content of redo record without CDC.

```
alter system dump logfile '/u01/app/oradata/TEST/redo01.log'
   SCN MIN 82207671290 
   SCN MAX 82207671290;
```

and see data in this dump.
If the same strange data - new SR on metalling about corrupted data in redo.
If data are OK (i.e. we can parse it using Oracle JDBC) - new SR on metalink about LogMiner.

Best regards,
Aleksei

**Comment by amticianelli** [comment]
Hey Aleksei,

we will look for changing the size of the column. It really seems that is a problem of data quality...

I thank you again for all your time and the fast response!

Have a good day, Alberto.
