### ISSUE TITLE
error when didn't set initload table

### ISSUE THREAD

**Issue by sonnguyen-dba** [averemee-si/oracdc#3]
Hi Alexei,
Have nice a day!
I just have issue.

 ERROR WorkerSinkTask{id=oracdc-sink-oracle-0} Task threw an uncaught and unrecoverable exception. Task is being killrted. Error: null (org.apache.kafka.connect.runtime.WorkerSinkTask:565)
java.lang.NullPointerException
        at eu.solutions.a2.cdc.oracle.OraTable4SinkConnector.<init>(OraTable4SinkConnector.java:88)
        at eu.solutions.a2.cdc.oracle.OraCdcJdbcSinkTask.put(OraCdcJdbcSinkTask.java:107)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:545)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:200)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Regards,
Son

**Comment by averemee-si** [comment]
Hi Son,

Could you please clone latest code from GitHub and retest issue.
Fixed in [add OraBlob/OraClob support to Sink classes](https://github.com/averemee-si/oracdc/commit/64b0aa793226e4fc41081f690acb82399858e64e)

Regards,
Aleksei

**Comment by sonnguyen-dba** [comment]
Hi Aleksei,
Thank you a lot!
Regards,
Son
