### ISSUE TITLE
"Invalid value 2 for configuration a2.schema.type: String must be one of: kafka, single, debezium." with solutions.a2.cdc.oracle.OraCdcSourceConnector

### ISSUE THREAD

**Issue by dabadiejc** [averemee-si/oracdc#66]
hello !
here is the bug i've obtained with oracdc with materialized views : 

[2024-10-23 13:50:10,755] INFO [ora-source-yield|task-1] Starting oracdc Source Task for EMP (solutions.a2.cdc.oracle.OraCdcSourceTask:59)
[2024-10-23 13:50:10,755] ERROR [ora-source-yield|task-1] WorkerSourceTask{id=ora-source-yield-1} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:212)
org.apache.kafka.connect.errors.ConnectException: Couldn't start oracdc due to coniguration error
        at solutions.a2.cdc.oracle.OraCdcSourceTask.start(OraCdcSourceTask.java:64)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.initializeAndStart(AbstractWorkerSourceTask.java:280)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:77)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value 2 for configuration a2.schema.type: String must be one of: kafka, single, debezium
        at org.apache.kafka.common.config.ConfigDef$ValidString.ensureValid(ConfigDef.java:1016)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:502)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:486)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:114)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:134)
        at solutions.a2.cdc.oracle.OraCdcSourceConnectorConfig.<init>(OraCdcSourceConnectorConfig.java:402)
        at solutions.a2.cdc.oracle.OraCdcSourceTask.start(OraCdcSourceTask.java:62)
        ... 10 more
[2024-10-23 13:50:10,755] INFO [ora-source-yield|task-1] Stopping task. (solutions.a2.cdc.oracle.OraCdcSourceTask:154).

even if i force a2.schema.type in JSON file, i always obtain the same message : Invalid value 2 for configuration a2.schema.type: String must be one of: kafka, single, debezium.
thanks in advance
best regards

**Comment by averemee-si** [comment]
Working on it

**Comment by averemee-si** [comment]
Hello,

Is it possible to get an example of your configuration?

N.B. I also strongly recommend that you use another connector **solutions.a2.cdc.oracle.OraCdcLogMinerConnector** , which, unlike the connector for materialized views, does not create additional load for the database. All configuration details and a quick start with a docker container are described in - [How to Set Up Oracle Database Tables Replication in Minutes](https://averemee.substack.com/p/how-to-set-up-oracle-database-tables)

Best regards,
Aleksei

**Comment by dabadiejc** [comment]
Hello

Of course :

The JSON file :
***@***.*** tmp]$ cat ora-source-yield.json
{
   "name" : "ora-source-yield",
   "config" : {
     "connector.class" : "solutions.a2.cdc.oracle.OraCdcSourceConnector",
     "tasks.max" : "2",
     "errors.tolerance" : "none",
     "errors.log.enable" : "true",
     "errors.log.include.messages" : "true",
     "a2.poll.interval" : "20000",
     "a2.batch.size" : "10000",
     "a2.jdbc.url" : ***@***.***://10.18.39.221:1888/yield",
     "a2.jdbc.username" : "KAFKA",
     "a2.jdbc.password" : "thepasswd",
     "a2.oracdc.schemas" : "true",
     "a2.schema.type" : "debezium",
     "a2.include" : "KAFKA.%"
   }
}



The yaml file for the container :
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2-oracle-cdc-connector
  namespace: kafka
  labels:
    app: a2-oracle-cdc-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a2-oracle-cdc-connector
  template:
    metadata:
      labels:
        app: a2-oracle-cdc-connector
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: a2-oracle-cdc-connector
        image: docker.io/library/oracdc:2.5.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        env:
        - name: TZ
          value: "Europe/Paris"
        - name:   A2_ORACDC_BOOTSTRAP_SERVERS
          value: "broker-0-0.kafka-brkr-svc.kafka.svc.cluster.local:9093, broker-1-0.kafka-brkr-svc.kafka.svc.cluster.local:9093, broker-2-0.kafka-brkr-svc.kafka.svc.cluster.local:9093, broker-3-0.kafka-brkr-svc.kafka.svc.cluster.local:9093"
        - name: A2_ORACDC_GROUP_ID
          value: "connect-cluster"
        - name: A2_ORACDC_OFFSET_STORAGE_TOPIC
          value: "connect-offsets"
        - name: A2_ORACDC_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: A2_ORACDC_CONFIG_STORAGE_TOPIC
          value: "connect-configs"
        - name: A2_ORACDC_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: A2_ORACDC_STATUS_STORAGE_TOPIC
          value: "connect-status"
        - name: A2_ORACDC_STATUS_STORAGE_REPLICATION_FACTOR
          value: "1"


the database is strictly the example of your documentation….

We are testing this connector specifically for materialized views, we have already an internal solution based on logminer.

Thanks in advance for your support
Best regards
JC

**Comment by averemee-si** [comment]
Hello,

Mea culpa!

Fixed in [fix for #66](https://github.com/averemee-si/oracdc/commit/e9eb0afd2222b1fb863bf205f5115efc1a1e02c5)
Latest docker image is [here](https://hub.docker.com/layers/averemee/oracdc/latest/images/sha256-81f6ffaa6e58aa3ec710aac908b58434ed83097b0fc2a7fd03229e51669b42d4?context=repo)

If you need real-time when using the LogMiner connector, feel free to contact me (I'm in CET TZ) - I have customers with configurations where a maximum of 30 seconds lag from the moment a record is committed in Oracle to the moment a record appears in Kafka without any additional load on the RDBMS.
P.S. Also in December of this year, we will release a connector that will read and parse Oracle redo files directly without using LogMiner (like AWS DMS binary reader)

**Comment by dabadiejc** [comment]
Hello
Thank you so much !!
Connection is ok.

I’m checking internally with my colleagues for your 2 propositions.
Best regards
JC

**Comment by dabadiejc** [comment]
Hello
Could you give more details about your future release which permits you to read and parse Oracle redo files directly without using LogMiner ?
Is it a mechanism similar to Oracle Golden gate ?
Thank you in advance
Best regards
JC

**Comment by dabadiejc** [comment]
Hello


Just a question on your PS : “Also in December of this year, we will release a connector that will read and parse Oracle redo files directly without using LogMiner (like AWS DMS binary reader)”

Do you deliver this new connector ?

If yes, can I test it ?

Best regards

JC
