### ISSUE TITLE
java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by sonnguyen-dba** [averemee-si/oracdc#9]
Hi Aleksej,

Could you please help me with issue?

[root@oracdc46 oracdc]# du -sh trans/
158G    trans/
[root@oracdc46 oracdc]# ls -l trans | wc -l
523939

[root@oracdc46 kafka]# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1031062
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
**open files                      (-n) 1048576**
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 32768
cpu time               (seconds, -t) unlimited
max user processes              (-u) 6815744
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

[root@oracdc46 oracdc]# ps -ef | grep oracdc
avahi      684     1  0 Nov13 ?        00:00:00 avahi-daemon: running [oracdc46.local]
root     10773     1 71 Nov14 ?        16:55:09 /opt/jdk-11.0.8/bin/java -Xms16G -Xmx16G -XX:MaxDirectMemorySize=224G -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -XX:MaxInlineLevel=15 -Djava.awt.headless=true -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dkafka.logs.dir=/data/kafka/bin/../logs -Dlog4j.configuration=file:/data/kafka/bin/../etc/kafka/connect-log4j.properties -cp /data/oracdc/target/lib/HikariCP-3.4.1.jar:/data/oracdc/target/lib/affinity-3.2.2.jar:/data/oracdc/target/lib/annotations-12.0.jar:/data/oracdc/target/lib/chronicle-bytes-2.17.49.jar:/data/oracdc/target/lib/chronicle-core-2.17.35.jar:/data/oracdc/target/lib/chronicle-queue-5.17.43.jar:/data/oracdc/target/lib/chronicle-threads-2.17.27.jar:/data/oracdc/target/lib/chronicle-wire-2.17.71.jar:/data/oracdc/target/lib/commons-cli-1.4.jar:/data/oracdc/target/lib/commons-lang3-3.8.1.jar:/data/oracdc/target/lib/commons-math3-3.6.1.jar:/data/oracdc/target/lib/compiler-2.3.4.jar:/data/oracdc/target/lib/hamcrest-core-1.3.jar:/data/oracdc/target/lib/jackson-annotations-2.10.0.jar:/data/oracdc/target/lib/jackson-core-2.10.0.jar:/data/oracdc/target/lib/jackson-databind-2.10.0.jar:/data/oracdc/target/lib/jna-4.2.1.jar:/data/oracdc/target/lib/jna-platform-4.2.1.jar:/data/oracdc/target/lib/ojdbc8-19.7.0.0.jar:/data/oracdc/target/lib/ons-19.7.0.0.jar:/data/oracdc/target/lib/oraclepki-19.7.0.0.jar:/data/oracdc/target/lib/osdt_cert-19.7.0.0.jar:/data/oracdc/target/lib/osdt_core-19.7.0.0.jar:/data/oracdc/target/lib/simplefan-19.7.0.0.jar:/data/oracdc/target/lib/ucp-19.7.0.0.jar:/data/oracdc/target/lib/postgresql-42.2.14.jar:/data/oracdc/target/oracdc-kafka-0.9.7.2.jar:/data/kafka/share/java/confluent-security/connect/*:/data/kafka/share/java/kafka/*:/data/kafka/share/java/confluent-.....
.....
......
[root@oracdc46 fd]# ls -l /proc/10773/fd | wc -l
1048576

full max open file

[2020-11-14 21:39:09,094] WARN Failback to readonly tablestore (net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder:42)
net.openhft.chronicle.core.io.IORuntimeException: file=/data/oracdc/trans/0D88001E002C67D3.12161216233696012408/metadata.cq4t
        at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.build(SingleTableBuilder.java:123)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.initializeMetadata(SingleChronicleQueueBuilder.java:431)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.preBuild(SingleChronicleQueueBuilder.java:996)
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueBuilder.build(SingleChronicleQueueBuilder.java:329)
        at eu.solutions.a2.cdc.oracle.OraCdcTransaction.<init>(OraCdcTransaction.java:86)
        at eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread.run(OraCdcLogMinerWorkerThread.java:511)
Caused by: java.io.IOException: Too many open files
        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.base/java.io.File.createNewFile(File.java:1026)
        at net.openhft.chronicle.queue.impl.table.SingleTableBuilder.build(SingleTableBuilder.java:95)
        ... 5 more
[2020-11-14 21:39:09,096] WARN Forcing queue to be readOnly (net.openhft.chronicle.queue.impl.single.SingleChronicleQueue:158)
[2020-11-14 21:39:09,099] ERROR Unable to create Chronicle Queue! (eu.solutions.a2.cdc.oracle.OraCdcTransaction:99)
[2020-11-14 21:39:09,100] ERROR Can't append to a read-only chronicle
java.lang.IllegalStateException: Can't append to a read-only chronicle
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.acquireAppender(SingleChronicleQueue.java:414)
        at eu.solutions.a2.cdc.oracle.OraCdcTransaction.<init>(OraCdcTransaction.java:88)
        at eu.solutions.a2.cdc.oracle.OraCdcLogMinerWorkerThread.run(OraCdcLogMinerWorkerThread.java:511)
 (eu.solutions.a2.cdc.oracle.OraCdcTransaction:100)

Regards,
Son

**Comment by averemee-si** [comment]
Hi Son,

I need output of
```
cat /proc/sys/fs/file-max
```
Regards,
Aleksei

**Comment by sonnguyen-dba** [comment]
Hi Aleksej,

[root@oracdc46 fd]# cat /proc/sys/fs/file-max
6815744

Regards,
Son

**Comment by averemee-si** [comment]
Hi Son,

Thank you.
Please follow steps below:
1) Evaluate options for running connector not as **root**
2) Optionally increase  value of **fs.file-max** in **/etc/sysctl.conf** (looks like you have sysctl.conf values after oracle-database-preinstall-VERSION.rpm)
3) Increase soft and hard open file limits for user running connector in **/etc/security/limits.conf**. This number should be lower than value of **fs.file-max** and greater than simultaneous number of transactions in RDBMS instance multiplied by 2.

Regards,
Aleksei

**Comment by sonnguyen-dba** [comment]
Hi Aleksej, 
Thank you very much for your helping!
I'll trying and I can have a look at it in a days and report.
Regards,
Son

**Comment by sonnguyen-dba** [comment]
Hi Aleksej,
Thank you very much!
Running connector as oracdc working good!
Regards
Son
